### ISSUE TITLE
Money controller mod

### ISSUE THREAD

**Issue by LutherZhao** [Wayzware/AchievementEnabler#1]
hey thank you for your awesome mods! I was wondering if you could make a mod similar to the [PlayerMoneyController ](https://github.com/Mbyron26/PlayerMoneyController) that looks to be now abandoned?

**Comment by Wayzware** [comment]
Hey,
I will not be making a mod with that functionality unfortunately. You could try asking on one of the C:S2 modding discord servers if someone else wants to pick it up: [Server 1](https://discord.gg/4VHARkXz) or [Server 2](https://discord.gg/3ubm4jc7)
